AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Layout/LineLength:
  Max: 145
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 120
Metrics/BlockNesting:
  Max: 4
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/MethodLength:
  Max: 30
Metrics/ParameterLists:
  Max: 5
Metrics/PerceivedComplexity:
  Max: 17