databases:
  - name: khedutmall-rails
    databaseName: khedutmall_development
    user: khedutmall-rails

services:
  - type: web
    name: khedutmall-rails
    env: ruby
    branch: deploy-staging
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb -e staging"
    envVars:
      - key: RAILS_ENV
        value: staging
      - key: DATABASE_URL
        fromDatabase:
          name: khedutmall-rails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
